name = "xo"
version = "1.0.0"
description = "The essentials of Tic-tac-toe extracted into a library."
licences = ["BSD-3-Clause"]
repository = { type = "github", user = "dwayne", repo = "gleam-xo" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
prng = ">= 4.0.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
